language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
script:
- mvn clean install
- build=$(grep "Open Liberty" target/liberty/wlp/usr/servers/defaultServer/logs/console.log
  | cut -d' ' -f5 | cut -d')' -f1 ); release=$( echo "$build" | cut -d'/' -f1); number=$(
  echo "$build" | cut -d'/' -f2); ol_jv=$(grep -i "on java" target/liberty/wlp/usr/servers/defaultServer/logs/console.log);
  jv=$(printf '%s\n' "${ol_jv//$' on '/$'\n'}" | sed '2q;d'); echo -e "\n"; echo -e  "\033[1;34mOpen
  Liberty release:\033[0m \033[1;36m$release\033[0m"; echo -e "\033[1;34mOpen Liberty
  build number:\033[0m \033[1;36m$number\033[0m"; echo -e "\033[1;34mJava version:\033[0m
  \033[1;36m$jv\033[0m";
- cd target/liberty/wlp/usr/servers/defaultServer/logs/; repo_name=$(echo "$TRAVIS_REPO_SLUG"
  | sed -e "s/\//-/g"); if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then result="passed";
  else result="failed"; fi; serverlogsarchive="$repo_name-$TRAVIS_BUILD_NUMBER-$result.zip";zip
  -r "$serverlogsarchive" .; curl -H "$JFROG_TOKEN" -T "$serverlogsarchive" "https://na.artifactory.swg-devops.com/artifactory/hyc-openliberty-guides-files-generic-local/";
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: MqCcp8pvGWNTz+C68fSjYTfJnI+8WH+32uJ6G80lHqAc/rhdOsXsEh4j6BJ3aqKvA3sawiYmz2gfGYbq6r+nigddM6UNVqyN1hpF1u2x/56mosCO5CJUxzZpylvF3JvQuhja9bySTYoKyuskxLbjkxIE8nifQhm+Op3U1pg3DAymJq311Z3dl1T6G7C+In1L7JoNudZUNIj4PolXWiOH0EBUSVD+mEA3432mBzoyppEHDMl90j+FRgP6ElSH0x6+A4Clxniqw1yAHIyt3RmwrEKVJxBpQBCZLFRrYvCIUN0tvw7Rc5L2cV3YSQgl0btpSnW6YOLK4fBBHGi4sBDpqHcYDidXSTkPqUpCeoNmwvVWdi3uZLR7Z0GDZF5bfEfS3NwEREzH7bA1e1wnzDz3Cd/3SqlyYD3ss2PU8ET+ltQNzxO5W5ylHY3Qz9efciLlp+jPzNJKFzA9QkE1IuUs/1mUx2I9gUCW6bfmozNV6zN0CKDiwWsQdB2yemNjhqNKksGwE/LnDQJWWVb3nvV0gmdOXhEZNTuylYaeS9zD8fssXp8+R7q9yUCZlpPKtVhJcTlYQG466ZVEPUCYc3tkUaLrMnUsdBIBpvrLKShAXBBRAc2YrR+S4Ni9FN9kGw6QsrpYv/aDeBvkY0HMy1AyYa+0mAMhapUt5RtxBh94I30=
    on_success: never
    on_failure: always
branches:
  only:
  - master
