// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-openapi
:page-layout: guide
:page-duration: 15 minutes
// :page-releasedate: 2017-12-11
:page-description: Learn how to expose and filter RESTful APIs from code or static files using MicroProfile OpenAPI.
:page-tags: ['MicroProfile', 'OpenAPI']
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Exposing RESTful APIs

Learn how to expose and filter RESTful APIs from code or static files using MicroProfile OpenAPI.


:openapi-url: http://localhost:9080/openapi
:inv-url: http://localhost:9080/inventory/systems
:sys-url: http://localhost:9080/inventory/properties


== What you'll learn

You will learn how to expose and filter RESTful APIs from annotations, static OpenAPI files, and/or
OpenAPI trees using MicroProfile OpenAPI.

The OpenAPI specification (previously known as the Swagger specification) defines a standard interface
for exposing RESTful APIs which enables both humans and computers to understand the functionalities of
services without requiring direct access to the source code or documentation. The MicroProfile OpenAPI
specification aims to provide a set of Java interfaces and programming models which allow Java developers
to natively produce OpenAPI v3 documents from their JAX-RS applications.

You will expose the RESTful APIs of the provided `inventory` service. Note, if you have read through
some of the other MicroProfile guides, you may recognize the code you will be working with. While the
application still functions the same way, the `system` service has been merged into the `inventory`
service due a current limitation of MicroProfile OpenAPI v1.0 of supporting multiple JAX-RS applications.
As a result, the `properties` resource of the `system` service is now served at `inventory/properties`
rather than `system/properties`.

You can find the complete MicroProfile OpenAPI spec on its official GitHub repistory:
https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


=== Try what you'll build

The `finish` directory in the root directory of this guide contains contains the fully exposed `inventory`
service. Feel free to give it a try before you proceed.

To try out the service, navigate to the `finish` directory and then run the Maven `install` and
`liberty:start-server` goals to build and run the service in Open Liberty:

```
cd finish
mvn install liberty:start-server
```

// I think here I can say "you'll see" because its still part of the same sentence and its assumed that the user
// will finish reading the sentence first before doing anything. If it were two sentences, then it would be "You see".
Next, point your browser to {openapi-url} and you'll see the RESTful APIs of the `inventory` service.
You can also point to {openapi-url}/ui for a more interactive view of the deployed APIs.

Once you are done checking out the service and its APIs, stop Open Liberty:

```
mvn liberty:stop-server
```


// =================================================================================================
// Generating APIs
// =================================================================================================

== Generating the OpenAPI document for the inventory service

There are a variety of ways to go about generating the resulting OpenAPI document. First of all, because
all JAX-RS annotations are processed by default, you can augment your existing JAX-RS annotations with
OpenAPI annotations to enrich your APIs with minimal amount of work. Second, you can use a set of predefined
models to manually create all elements of the OpenAPI tree. Finally, you can filter various elements of the
OpenAPI tree, changing them to your liking or removing them entirely.

Before you proceed, try deploying the current `inventory` service and checking the resulting document.
Because the JAX-RS framework handles basic API generation for JAX-RS annotations, you will see a skeleton
of your OpenAPI tree. To do this, navigate to the `start` directory in the root directory of the guide,
then build and run the service using Maven:

```
cd start
mvn clean install liberty:start-server
```

The `install` goal builds the application and creates a `.war` file in the `target` directory. It also
configures and installs Open Liberty into the `target/liberty/wlp` directory. The `liberty:start-server`
goals starts the built application in Open Liberty.

Now point to {openapi-url} to see the generated OpenAPI document.


=== Augmenting the existing JAX-RS annotations with OpenAPI annotations

As mentioned previously, because all JAX-RS annotations are processed by default, you can augment your
existing JAX-RS annotations with OpenAPI annotations without having to re-write portions of the OpenAPI
document that are already covered by the JAX-RS framework.

Add OpenAPI annotations to the two JAX-RS methods in the `src/main/java/io/openliberty/guides/inventory/InventoryResource.java` class:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=**;!copyright]
----

Let's break down the new annotations:

[cols="35, 200"]
|===
| *Annotation*    | *Description*
| `@APIResponses` | A container for multiple responses from an API operation. This annotation is
optional, but it can be helpful to organize a method with multiple responses.
| `@APIResponse`  | Describes a single response from an API operation.
| `@Content`      | Provides schema and examples for a particular media type.
| `@Schema`       | Allows the definition of input and output data types.
| `@Operation`    | Describes an operation or typically a HTTP method against a specific path.
| `@Parameter`    | Describes a single operation parameter.
|===

At this point, you can run the `mvn package` command to rebuild the application. Then refresh {openapi-url}
to see the updated OpenAPI tree. The two endpoint your JAX-RS methods are served at will now be more
meaningful:

[source, YAML, role="no_copy"]
----
/inventory/systems/{hostname}:
  get:
    summary: Get JVM system properties for particular host
    description: Retrieves and returns the JVM system properties from the system
      service running on the particular host.
    operationId: getPropertiesForHost
    parameters:
    - name: hostname
      in: path
      description: The host for whom to retrieve the JVM system properties for.
      required: true
      schema:
        type: string
      example: foo
    responses:
      404:
        description: Missing description - to be filtered.
        content:
          none: {}
      200:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'
/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/InventoryList'
----

You may also add OpenAPI annotation to POJOs. Augment the `src/main/java/io/openliberty/guides/inventory/model/InventoryList.java`
POJO with OpenAPI annotations:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java[tags=**;!copyright]
----

Once again, run `mvn package` and refresh {openapi-url} to see the updated OpenAPI tree:

[source, YAML, role="no_copy"]
----
components:
  schemas:
    InventoryList:
      required:
      - systems
      type: object
      properties:
        systems:
          type: array
          items:
            $ref: '#/components/schemas/System'
        total:
          type: integer
      description: POJO that represents the inventory contents.
    Properties:
      type: object
      additionalProperties:
        type: string
    System:
      required:
      - hostname
      - properties
      type: object
      properties:
        hostname:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
      description: POJO that represents a single inventory entry.
----


=== Bootstrapping the OpenAPI tree using the `OASFactory`

Alternatively to using OpenAPI annotations, you can use the `OASFactory` class to manually create any
elements of the OpenAPI tree from the `org.eclipse.microprofile.openapi.models` package.

Notice that your current OpenAPI document doesn't provide much information on the application itself,
as well as what server and port it runs on (`info` and `servers` elements). This can be defined like so
using the `OASFactory`:

[source, Java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java[tags=oasfactory]
----

For now, hold off from copying this code anywhere. It will fit nicely into the class you'll create
in the next section.

While you can create parts of the OpenAPI tree using the `OASFactory` class, you can also create the
entire tree by implementing the `OASModelReader` interface. However, because this class would turn out
to be be extremely long, you will not be creating it here. Instead, feel free to take a look at the
following example in the official MicroProfile OpenAPI GitHub repository:

https://github.com/arthurdm/microprofile-open-api/blob/master/tck/src/main/java/org/eclipse/microprofile/openapi/reader/MyOASModelReaderImpl.java


=== Filtering the OpenAPI tree elements

There may be scenarios where you may wish to update or remove certain elements and fields of the OpenAPI
document. This can be done using the `OASFilter` interface.

Implement `OASFilter` in the `src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java` class:

[source, Java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java[tags=**;!copyright]
----

The `filterAPIResponse()` method allows filtering of a particular `APIResponse`. In this case, you are
filling in the previously missing description for the `404` response returned by the `/inventory/systems/<badhostname>`
endpoint. To remove an `APIResponse`, or any other filterable element in general, return `null`.

The `filterOpenAPI()` method allows filtering of the singleton `OpenAPI` element. Recall the `OASFactory`
example from the previous section. Use that code in this method to create the missing `Info` and `Server`
elements. Note that this is the only element which cannot be removed. Note also that this method is
always called last for a given filter. Hence, make sure that it doesn't overwrite any other filter
operations that are called before it.

Each filtering method is called once for each corresponding element in the model tree. You can think
of each such method as a callback for various key OpenAPI elements.

Next, you must register your newly created filter class in order to use it. This can be done using MicroProfile Config.
Create the following configuration file `src/main/webapp/META-INF/microprofile-config.properties`:

```
mp.openapi.filter = io.openliberty.guides.inventory.filter.InventoryOASFilter
```

By passing in the fully qualified name of the filter class into the `mp.openapi.filter` configuration key,
you are registering your filter.

Finally, run `mvn package` and refresh {openapi-url} to see the updated OpenAPI tree:
[source, yaml, role="no_copy"]
----
info:
  title: Inventory App
  description: Application for storing JVM system properties of various hosts.
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: "1.0"
servers:
- url: http://localhost:{port}
  description: Simple Open Liberty.
  variables:
    port:
      description: Server HTTP port.
      default: "9080"
----

To learn more about what elements you can filter, visit the official MicroProfile OpenAPI GitHub repistory:
https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFilter.java


// =================================================================================================
// Pre-generated APIs
// =================================================================================================

== Using pre-generated OpenAPI documents

As an alternative means to generating the OpenAPI model tree from code, you can include a valid pre-generated
OpenAPI document. Depending on the scenario, the document may be fully complete or partially complete.
Every such document is required to be named `openapi` with an extension of `yml`, `yaml`, or `json` and
be provided under the `META-INF` directory. If more than one document is found that matches one of these
extensions, then the behaviour for choosing this file is underfined.

We are providing you with a complete OpenAPI document under `src/main/webapp/META-INF/openapi.yaml`.
This document is the same as your current OpenAPI document, with the exception that it contains the
missing APIs for the `/inventory/properties` endpoint. In order to use this document, you must set
the `mp.openapi.scan.disable` property to `true` in the `microprofile-config.properties` file:

```
mp.openapi.filter = io.openliberty.guides.inventory.filter.InventoryOASFilter
mp.openapi.scan.disable = true
```

Run `mvn package` and refresh {openapi-url} to see the updated OpenAPI tree:

[source, yml, role="no_copy"]
----
/inventory/properties:
  get:
    summary: Get JVM system properties.
    description: Returns the JVM system properties for the host running this service.
    operationId: getProperties
    responses:
      200:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'
----


// =================================================================================================
// Building the application
// =================================================================================================

// include::{common-includes}/mvnbuild.adoc[]
//
// You can find the `inventory` and `system` services at:
//
// - {inv-url}
// - {sys-url}
//
// include::{common-includes}/mvnpackage.adoc[]


// =================================================================================================
// Testing the services
// =================================================================================================

== Testing the service

A few tests have been included for you to test the basic functionality of the `inventory` service. If a test
failure occurs, then you must have introduced a bug into the code. These tests will run automatically
as a part of the Maven build process (when you run `mvn install`). You can also run these tests separately
from the build using the `mvn verify` command, but make sure that the server is stopped beforehand.

No explicit tests exist to verify the correctness of the generated OpenAPI tree. This can be verified
manually by visiting {openapi-url} or {openapi-url}/ui.


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have just exposed and filtered the APIs of the `inventory` service from both code and a static file
using MicroProfile OpenAPI.

Feel free to try one of the related MicroProfile guides. They demonstrate new technologies that you
can learn and expand on top what you built here.

For more in-depth examples of MicroProfile OpenAPI, try one of the demo applications found on the official
MicroProfile OpenAPI GitHub repository:
https://github.com/eclipse/microprofile-open-api/tree/master/tck/src/main/java/org/eclipse/microprofile/openapi/apps


include::{common-includes}/finish.adoc[]
