// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-openapi
:page-layout: guide
:page-duration: 15 minutes
// :page-releasedate: 2017-12-11
:page-description: Learn how to expose and filter RESTful APIs from code or static files using MicroProfile OpenAPI.
:page-tags: ['MicroProfile', 'OpenAPI']
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Exposing RESTful APIs

Learn how to expose and filter RESTful APIs from code or static files using MicroProfile OpenAPI.


:openapi-url: http://localhost:9080/openapi
:inv-url: http://localhost:9080/inventory/systems
:sys-url: http://localhost:9080/inventory/properties


== What you'll learn

You will learn how to expose and filter RESTful APIs from annotations, static OpenAPI files, and/or
OpenAPI trees using MicroProfile OpenAPI.

The OpenAPI specification (previously known as the Swagger specification) defines a standard interface
for exposing RESTful APIs which enables both humans and computers to understand the functionalities of
services without requiring direct access to the source code or documentation. The MicroProfile OpenAPI
specification, aims to provide a set of Java interfaces and programming models which allow Java developers
to natively produce OpenAPI v3 documents from their JAX-RS applications.

You will expose the RESTful APIs of the provided `inventory` service. Note, if you have read through
some of the other MicroProfile guides, you may recognize the code you will be working with. While the
application still functions the same way, the `system` service has been merged into the `inventory`
service due a current limitation of MicroProfile OpenAPI v1.0 of supporting multiple JAX-RS applications.
As a result, the `properties` resource of the `system` service is now served at `inventory/properties`
rather than `system/properties`.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


=== Try what you'll build

The `finish` directory in the root directory of this guide contains contains the fully exposed `inventory`
service. Feel free to give it a try before you proceed.

To try out the service, navigate to the `finish` directory and then run the Maven `install` and
`liberty:start-server` goals to build and run the service in Open Liberty:

```
cd finish
mvn install liberty:start-server
```

// I think here I can say "you'll see" because its still part of the same sentence and its assumed that
// the user will finish reading the sentence first before doing anything. If it were two sentences, then
// it would be "You see".
Next, point your browser to {openapi-url} and you'll see the RESTful APIs of the `inventory` service.
You can also point to {openapi-url}/ui for a more interactive view of the deployed APIs.

Once you are done checking out the services, stop both Open Liberty servers:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.


// =================================================================================================
// Main
// =================================================================================================

https://github.com/eclipse/microprofile-open-api/tree/master/tck/src/main/java/org/eclipse/microprofile/openapi/apps

Annotations:
1. Enable the feature to see the skeleton document generated
2. Demonstrate annotating simple methods (list method)
3. Demonstrate annotating slightly more complex methods, with multiple responses (system/<hostname>)
4. Demonstrate annotating a POJO (InvList?)

Static OpenAPI files:
- show how this can be done for the system service

Programming model:

Filter:
- filter description for APIResponse and change it
- mention that in order to get rid of an element, then null can be returned.


Processing rules:
- dont need to talk about these?

other:
- talk about limitations (restriction to one app) + everything else in section 5
- link to existing demo apps
- cannot have more than one jax-rs application

// =================================================================================================
// Building the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

You can find the `inventory` and `system` services at:

- {inv-url}
- {sys-url}

include::{common-includes}/mvnpackage.adoc[]



// =================================================================================================
// Testing the services
// =================================================================================================



// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have just

Feel free to try one of the related MicroProfile guides. They demonstrate new technologies that you can learn and
expand on top what you built here.

include::{common-includes}/finish.adoc[]
