// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-openapi
:page-layout: guide
:page-duration: 15 minutes
// :page-releasedate: 2017-12-11
:page-description: Explore how to expose and filter RESTful APIs from code or static files by using MicroProfile OpenAPI.
:page-tags: ['MicroProfile', 'OpenAPI', 'microservices', '@APIResponse', '@Schema', '@Content', '@Operation', '@Info', '@Parameter']
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro', 'microprofile-config']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Exposing RESTful APIs

Explore how to expose and filter RESTful APIs from code or static files by using MicroProfile OpenAPI.


:openapi-url: http://localhost:9080/openapi
:inv-url: http://localhost:9080/inventory/systems
:sys-url: http://localhost:9080/inventory/properties


== What you'll learn

You will learn how to expose and filter RESTful APIs from annotations, POJOs, and static OpenAPI
files by using MicroProfile OpenAPI.

The OpenAPI specification, previously known as the Swagger specification, defines a standard interface
for exposing RESTful APIs. This specification gives both humans and computers a better understanding
of the functionalities of services without requiring direct access to source code or documentation.
The MicroProfile OpenAPI specification provides a set of Java interfaces and programming models that
allow Java developers to natively produce OpenAPI v3 documents from their JAX-RS applications.

You will expose the RESTful APIs of the provided `inventory` service. If you have read through
some of the other MicroProfile guides, you might recognize this service. While the application still
functions the same way, the `system` service has been merged into the `inventory` service because of
a MicroProfile OpenAPI requirement that states "The 1.0 version of the MicroProfile OpenAPI specification
does not define how the `/openapi` endpoint may be partitioned in the event that the MicroProfile runtime
supports deployment of multiple applications". As a result, the `properties` resource of the `system`
service is now served at the `inventory/properties` endpoint rather than the `system/properties` endpoint.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


=== Try what you'll build

The `finish` directory in the root directory of this guide contains the fully exposed `inventory`
service. Feel free to give it a try before you proceed.

To try out the service, navigate to the `finish` directory and then run the Maven `install` and
`liberty:start-server` goals to build and run the service in Open Liberty:

```
cd finish
mvn install liberty:start-server
```

// I think here I can say "you'll see" because its still part of the same sentence and its assumed that the user
// will finish reading the sentence first before doing anything. If it were two sentences, then it would be "You see".
Next, point your browser to the {openapi-url} URL and you'll see the RESTful APIs of the `inventory`
service. You can also point to the {openapi-url}/ui URL for a more interactive view of the deployed APIs.

When you are done checking out the service and its APIs, stop Open Liberty:

```
mvn liberty:stop-server
```


// =================================================================================================
// Generating APIs
// =================================================================================================

== Generating the OpenAPI document for the inventory service

You can generate the resulting OpenAPI document in various ways. First, because
all JAX-RS annotations are processed by default, you can augment your existing JAX-RS annotations with
OpenAPI annotations to enrich your APIs with a minimal amount of work. Second, you can use a set of predefined
models to manually create all elements of the OpenAPI tree. Finally, you can filter various elements of the
OpenAPI tree, changing them to your liking or removing them entirely.

Before you proceed, try deploying the current `inventory` service and checking the resulting document.
Navigate to the `start` directory in the root directory of the guide. Then build and run the service
by using Maven:

```
cd start
mvn clean install liberty:start-server
```

Because the JAX-RS framework handles basic API generation for JAX-RS annotations, you will see a skeleton
of your OpenAPI tree.

The `install` goal builds the application and creates a `.war` file in the `target` directory. It also
configures and installs Open Liberty into the `target/liberty/wlp` directory. The `liberty:start-server`
goal starts the built application in Open Liberty.

Now, point to the {openapi-url} URL to see the generated OpenAPI document.


=== Augmenting the existing JAX-RS annotations with OpenAPI annotations

Because all JAX-RS annotations are processed by default, you can augment your existing JAX-RS annotations
with OpenAPI annotations, and you do not need to rewrite portions of the OpenAPI document that are
already covered by the JAX-RS framework.

Add OpenAPI annotations to the two JAX-RS methods in the `src/main/java/io/openliberty/guides/inventory/InventoryResource.java` file:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=**;!copyright]
----

Let's break down the new annotations:

[cols="35, 200"]
|===
| *Annotation*    | *Description*
| `@APIResponses` | A container for multiple responses from an API operation. This annotation is
optional, but it can be helpful to organize a method with multiple responses.
| `@APIResponse`  | Describes a single response from an API operation.
| `@Content`      | Provides a schema and examples for a particular media type.
| `@Schema`       | Defines the input and output data types.
| `@Operation`    | Describes a single API operation on a path.
| `@Parameter`    | Describes a single operation parameter.
|===

At this point, you can run the `mvn package` command to rebuild the application. Then, refresh the
{openapi-url} URL to see the updated OpenAPI tree. The two endpoints at which your JAX-RS methods are
served are now more meaningful:

[source, YAML, role="no_copy"]
----
/inventory/systems/{hostname}:
  get:
    summary: Get JVM system properties for particular host
    description: Retrieves and returns the JVM system properties from the system
      service running on the particular host.
    operationId: getPropertiesForHost
    parameters:
    - name: hostname
      in: path
      description: The host for whom to retrieve the JVM system properties for.
      required: true
      schema:
        type: string
      example: foo
    responses:
      404:
        description: Missing description - to be filtered.
        content:
          text/plain: {}
      200:
        description: JVM system properties of a particular host.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'
/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        description: host:properties pairs stored in the inventory.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryList'
----

You can also add OpenAPI annotations to POJOs. Augment the `src/main/java/io/openliberty/guides/inventory/model/InventoryList.java`
POJO with OpenAPI annotations:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java[tags=**;!copyright]
----

Again, run the `mvn package` command and refresh the {openapi-url} URL to see the updated OpenAPI tree:

[source, YAML, role="no_copy"]
----
components:
  schemas:
    InventoryList:
      required:
      - systems
      type: object
      properties:
        systems:
          type: array
          items:
            $ref: '#/components/schemas/System'
        total:
          type: integer
      description: POJO that represents the inventory contents.
    Properties:
      type: object
      additionalProperties:
        type: string
    System:
      required:
      - hostname
      - properties
      type: object
      properties:
        hostname:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
      description: POJO that represents a single inventory entry.
----


=== Filtering the OpenAPI tree elements

You might want to update or remove certain elements and fields of the OpenAPI document. All of this
can be done using the `OASFilter` interface.

Implement the `OASFilter` interface in the `src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java` file:

[source, Java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java[tags=**;!copyright]
----

Use the `filterAPIResponse()` method to filter a particular `APIResponse` element. In this case, you are
filling in the previously missing description for the `404` response that is returned by the `/inventory/systems/<badhostname>`
endpoint. To remove a `APIResponse` element, or another filterable element, return a `null` value.

Use the `filterOpenAPI()` method the filter the singleton `OpenAPI` element. Notice that your
current OpenAPI document doesn't provide much information on the application itself or the
server and port it runs on. This information is provided in the `info` and `servers` elements, which
are currently missing. You can use the `OASFactory` class to manually set these elements, and in general
any element of the OpenAPI tree from the `org.eclipse.microprofile.openapi.models` package. Note, the
`OpenAPI` element is the only element that cannot be removed since that would mean removing the whole
OpenAPI tree. This method is always called last for a given filter. Hence, make sure that it doesn't
override any other filter operations that are called before it.

Each filtering method is called once for each corresponding element in the model tree. You can think
of each method as a callback for various key OpenAPI elements.

Before you can use the filter class you created, create the `src/main/webapp/META-INF/microprofile-config.properties`
configuration file with the following content:

```
mp.openapi.filter = io.openliberty.guides.inventory.filter.InventoryOASFilter
```

This configuration file uses MicroProfile Config and registers your filter by passing in the fully
qualified name of the filter class into the `mp.openapi.filter` property.

Finally, run the `mvn package` command and refresh the {openapi-url} URL to see the updated OpenAPI tree:

[source, yaml, role="no_copy"]
----
info:
  title: Inventory App
  description: App for storing JVM system properties of various hosts.
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: "1.0"
servers:
- url: http://localhost:{port}
  description: Simple Open Liberty.
  variables:
    port:
      description: Server HTTP port.
----

[source, yaml, role="no_copy"]
----
404:
  description: Invalid hostname or the system service may not be running on
    the particular host.
  content:
    text/plain: {}
----

// Later this should be changed to:
// For more information about which elements you can filter, read the official MicroProfile 1.3 API.
For more information about which elements you can filter, look at the official `OASFilter` implementation
https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFilter.java[implementation].

To learn more about MicroProfile Config, visit the official MicroProfile GitHub https://github.com/eclipse/microprofile-config[repository]
and try one of our MicroProfile Config guides.


// =================================================================================================
// Pre-generated APIs
// =================================================================================================

== Using pre-generated OpenAPI documents

As an alternative to generating the OpenAPI model tree from code, you can include a valid pre-generated
OpenAPI document. This document must be named `openapi` with a `yml`, `yaml`, or `json` extension and
be provided under the `META-INF` directory. If more than one document is found that matches one of these
extensions, then the behavior for choosing this file is undefined. Depending on the scenario, the document
may be fully or partially complete. If the document is fully complete, then you can disable
annotation scanning by setting the `mp.openapi.scan.disable` MicroProfile Config property to `true`.
If the document is partially complete, then you can augmented it with further code or filters.

We are providing you with a complete OpenAPI document in the `src/main/webapp/META-INF/openapi.yaml` file.
This document is the same as your current OpenAPI document, but it contains the missing APIs for the
`/inventory/properties` endpoint. Open this document in your favorite text editor and uncomment all
of its lines. Because this OpenAPI document is complete, you no longer need the OpenAPI annotations
you defined previously. You don't have to explicitly remove these annotations. Instead simply set the
`mp.openapi.scan.disable` property to `true` in the `src/main/webapp/META-INF/microprofile-config.properties` file:

```
mp.openapi.filter = io.openliberty.guides.inventory.filter.InventoryOASFilter
mp.openapi.scan.disable = true
```

Run the `mvn package` command and refresh the {openapi-url} URL to see the updated OpenAPI tree:

[source, yml, role="no_copy"]
----
/inventory/properties:
  get:
    summary: Get JVM system properties.
    description: Returns the JVM system properties for the host running this service.
    operationId: getProperties
    responses:
      200:
        description: JVM system properties of the host running this service.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'
----


// =================================================================================================
// Testing the services
// =================================================================================================

== Testing the service

A few tests are included for you to test the basic functionality of the `inventory` service, but not
including the generated OpenAPI tree. If a test failure occurs, then you might have introduced a bug
into the code. These tests will run automatically as a part of the Maven build process when you run
the `mvn install` command. You can also run these tests separately from the build by using the `mvn verify`
command, but first make sure that the server is stopped.

No explicit tests exist to verify the correctness of the generated OpenAPI tree. Manually verify the
tree by visiting the {openapi-url} or the {openapi-url}/ui URL.


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have just exposed and filtered the APIs of the `inventory` service from both the code and a static
file by using MicroProfile OpenAPI.

Feel free to try one of the related MicroProfile guides. They demonstrate additional technologies that you
can learn and expand on top of what you built here.

For more in-depth examples of MicroProfile OpenAPI, try one of the demo applications found on the official
MicroProfile OpenAPI GitHub
https://github.com/eclipse/microprofile-open-api/tree/master/tck/src/main/java/org/eclipse/microprofile/openapi/apps[repository].


include::{common-includes}/finish.adoc[]
