// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-openapi
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2018-03-16
:page-guide-category: microprofile
:page-essential: false
:page-description: Explore how to document and filter RESTful APIs from code or static files by using MicroProfile OpenAPI.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['cdi-intro', 'microprofile-config']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:guide-author: Open Liberty
= Documenting RESTful APIs

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to document and filter RESTful APIs from code or static files by using MicroProfile OpenAPI.


:openapi-url: http://localhost:9080/openapi
:inv-url: http://localhost:9080/inventory/systems
:sys-url: http://localhost:9080/inventory/properties


== What you'll learn

You will learn how to document and filter RESTful APIs from annotations, POJOs, and static OpenAPI
files by using MicroProfile OpenAPI.

The OpenAPI specification, previously known as the Swagger specification, defines a standard interface
for documenting and exposing RESTful APIs. This specification allows both humans and computers to
understand or process the functionalities of services without requiring direct access to underlying
source code or documentation. The MicroProfile OpenAPI specification provides a set of Java interfaces
and programming models that allow Java developers to natively produce OpenAPI v3 documents from their
JAX-RS applications.

You will document the RESTful APIs of the provided `inventory` service, which serves two endpoints,
`inventory/systems` and `inventory/properties`. These two endpoints function the same way as in the
other MicroProfile guides.

Before you proceed, note that the 1.0 version of the MicroProfile OpenAPI specification does
not define how the `/openapi` endpoint may be partitioned in the event of multiple JAX-RS applications
running on the same server. In other words, you must stick to one JAX-RS application per server instance
as the behaviour for handling multiple applications is currently undefined.


// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]


=== Try what you'll build

The `finish` directory in the root directory of this guide contains the fully documented `inventory`
service. Feel free to give it a try before you proceed.

To try out the service, navigate to the `finish` directory and then run the Maven `install` and
`liberty:start-server` goals to build and run the service in Open Liberty:

[role='command']
```
mvn install liberty:start-server
```

// I think here I can say "you'll see" because its still part of the same sentence and its assumed that the user
// will finish reading the sentence first before doing anything. If it were two sentences, then it would be "You see".
Next, point your browser to the {openapi-url}[{openapi-url}^] URL and you'll see the RESTful APIs of the `inventory`
service. You can also point to the {openapi-url}/ui[{openapi-url}/ui^] URL for a more interactive view of the deployed APIs.

When you are done checking out the service and its APIs, stop Open Liberty:
[role='command']
```
mvn liberty:stop-server
```


// =================================================================================================
// Generating APIs
// =================================================================================================

== Generating the OpenAPI document for the inventory service

You can generate an OpenAPI document in various ways. First, because
all JAX-RS annotations are processed by default, you can augment your existing JAX-RS annotations with
OpenAPI annotations to enrich your APIs with a minimal amount of work. Second, you can use a set of predefined
models to manually create all elements of the OpenAPI tree. Finally, you can filter various elements of the
OpenAPI tree, changing them to your liking or removing them entirely.

Before you proceed, deploy the `inventory` service to see the bare-bones OpenAPI document that is generated.
To deploy the `inventory` service, navigate to the `start` directory and run the Maven `install` phase and the `liberty:start-server` goal:

[role='command']
```
mvn install liberty:start-server
```

The `install` phase builds the application and packages it into the `target/mp-openapi.war` file.
It also downloads Open Liberty into the `target/liberty/wlp` directory and configures it to run the
application. The `liberty:start-server` goal starts an Open Liberty server instance.

Because the JAX-RS framework handles basic API generation for JAX-RS annotations, a skeleton OpenAPI
tree will be generated from the `inventory` service. You can use this tree as a starting point and
augment it with annotations and code to produce a complete OpenAPI document.

Now, point to the {openapi-url}[{openapi-url}^] URL to see the generated OpenAPI tree. You can also point to the
{openapi-url}/ui[{openapi-url}/ui^] URL for a more interactive view of the APIs.


=== Augmenting the existing JAX-RS annotations with OpenAPI annotations

Because all JAX-RS annotations are processed by default, you can augment the existing code with OpenAPI
annotations without needing to rewrite portions of the OpenAPI document that are already covered by
the JAX-RS framework.

[role='code_command hotspot file=0', subs="quotes"]
----
#Update the `InventoryResource` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----

[role="edit_command_text"]
Add OpenAPI annotations to the two JAX-RS methods, [hotspot=32-46 hotspot=48-52 file=0]`getPropertiesForHost()` and [hotspot=70-81 file=0]`listContents()`.


InventoryResource.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=**;!copyright]
----

Clearly, there are many more annotations now, so let's break them down:

[cols="35, 200", options="header"]
|===
| *Annotation*    | *Description*
| [hotspot=32-42 file=0]`@APIResponses` | A container for multiple responses from an API operation. This annotation is
optional, but it can be helpful to organize a method with multiple responses.
| [hotspot=34-37 file=0]`@APIResponse`  | Describes a single response from an API operation.
| [hotspot=41 file=0]`@Content`      | Provides a schema and examples for a particular media type.
| [hotspot=42 file=0]`@Schema`       | Defines the input and output data types.
| [hotspot=43-46 file=0]`@Operation`    | Describes a single API operation on a path.
| [hotspot=48-52 file=0]`@Parameter`    | Describes a single operation parameter.
|===

At this point, you can run the the following command to rebuild the application.
[role='command']
```
mvn compile
```
Then, refresh the {openapi-url}[{openapi-url}^]
URL to see the updated OpenAPI tree. The two endpoints at which your JAX-RS methods are
served are now more meaningful:

[source, YAML, role="no_copy"]
----
/inventory/systems/{hostname}:
  get:
    summary: Get JVM system properties for particular host
    description: Retrieves and returns the JVM system properties from the system
      service running on the particular host.
    operationId: getPropertiesForHost
    parameters:
    - name: hostname
      in: path
      description: The host for whom to retrieve the JVM system properties for.
      required: true
      schema:
        type: string
      example: foo
    responses:
      404:
        description: Invalid hostname or the system service may not be running on
          the particular host.
        content:
          text/plain: {}
      200:
        description: JVM system properties of a particular host.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'
/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        description: host:properties pairs stored in the inventory.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryList'
----


OpenAPI annotations can also be added to POJOs to describe what they represent. Currently, your OpenAPI
document doesn't have a very meaningful description of the `InventoryList` POJO and hence it's very
difficult to tell exactly what that POJO is used for. To describe the `InventoryList` POJO in more detail, augment the
`src/main/java/io/openliberty/guides/inventory/model/InventoryList.java` file with some OpenAPI annotations.

[role='code_command hotspot file=1', subs="quotes"]
----
#Update the `InventoryList` class.#
`src/main/java/io/openliberty/guides/inventory/model/InventoryList.java`
----

[role='edit_command_text']
Add OpenAPI annotations to the [hotspot=7 file=1]`InventoryList` class and the [hotspot=10 file=1]`systems` variable.

InventoryList.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java[tags=**;!copyright]
----

Likewise, annotate the `src/main/java/io/openliberty/guides/inventory/model/SystemData.java` POJO,
which is referenced in the `InventoryList` class.

[role='code_command hotspot file=2', subs="quotes"]
----
#Update the `SystemData` class.#
`src/main/java/io/openliberty/guides/inventory/model/SystemData.java`
----

[role='edit_command_text']
Add OpenAPI annotations to the [hotspot=6 file=2]`SystemData` class, the [hotspot=9 file=2]`hostname` variable and the [hotspot=12 file=2]`properties` variable.

SystemData.java
[source, Java, linenums, role="code_column"]
----
include::finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java[tags=**;!copyright]
----

Again, run the following command and refresh the {openapi-url}[{openapi-url}^] URL to see the updated OpenAPI tree.
[role='command']
```
mvn compile
```

[source, YAML, role="no_copy"]
----
components:
  schemas:
    InventoryList:
      required:
      - systems
      type: object
      properties:
        systems:
          type: array
          items:
            $ref: '#/components/schemas/SystemData'
        total:
          type: integer
      description: POJO that represents the inventory contents.
    SystemData:
      required:
      - hostname
      - properties
      type: object
      properties:
        hostname:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
      description: POJO that represents a single inventory entry.
    Properties:
      type: object
      additionalProperties:
        type: string
----


=== Filtering the OpenAPI tree elements

Filtering of certain elements and fields of the generated OpenAPI document can be done by using the
`OASFilter` interface.

[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryOASFilter` class.#
`src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java`
----

InventoryOASFilter.java
[source, Java, linenums, role="code_column"]
----
include::finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java[tags=**;!copyright]
----

The [hotspot=18-24 file=0]`filterAPIResponse()` method allows filtering of `APIResponse` elements. When you
override this method, it will be called once for every `APIResponse` element in the OpenAPI tree.
In this case, you are matching the `404` response that is returned by the `/inventory/systems/{hostname}`
endpoint and setting the previously missing description. To remove an `APIResponse` element
or another filterable element, simply return `null`.

The [hotspot=27-46 file=0]`filterOpenAPI()` method allows filtering of the singleton [hotspot=27 file=0]`OpenAPI` element. Unlike other filter
methods, when you override [hotspot=27-46 file=0]`filterOpenAPI()`, it is called only once as the last method
for a particular filter. Hence, make sure that it doesn't override any other filter operations that are
called before it. Your current OpenAPI document doesn't provide much information on the application
itself or on what server and port it runs on. This information is usually provided in the `info`
and `servers` elements, which are currently missing. Use the `OASFactory` class to manually set these
and other elements of the OpenAPI tree from the `org.eclipse.microprofile.openapi.models`
package. The `OpenAPI` element is the only element that cannot be removed since that would mean
removing the whole OpenAPI tree.

Each filtering method is called once for each corresponding element in the model tree. You can think
of each method as a callback for various key OpenAPI elements.

Before you can use the filter class that you created, you need to create the `microprofile-config.properties` file.

[role="code_command hotspot", subs="quotes"]
----
#Create the configuration file.#
`src/main/webapp/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, text, linenums, role="code_column"]
----
include::finish/src/main/webapp/META-INF/microprofile-config.properties[tags=config]
----

This configuration file is picked up automatically by MicroProfile Config and registers your filter
by passing in the fully qualified name of the filter class into the [hotspot=1 file=1]`mp.openapi.filter` property.

Finally, run the following command and refresh the {openapi-url}[{openapi-url}^] URL to see the updated OpenAPI tree.
[role='command']
```
mvn compile
```
[source, yaml, role="no_copy"]
----
info:
  title: Inventory App
  description: App for storing JVM system properties of various hosts.
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: 1.0.0
servers:
- url: http://localhost:{port}
  description: Simple Open Liberty.
  variables:
    port:
      default: "9080"
      description: Server HTTP port.
----

[source, yaml, role="no_copy"]
----
404:
  description: Invalid hostname or the system service may not be running on
    the particular host.
  content:
    text/plain: {}
----

For more information about which elements you can filter, see the https://openliberty.io/docs/ref/microprofile/[MicroProfile API^].

To learn more about MicroProfile Config, visit the MicroProfile Config https://github.com/eclipse/microprofile-config[GitHub repository^]
and try one of the MicroProfile Config https://openliberty.io/guides/?search=Config[guides^].


// =================================================================================================
// Pre-generated APIs
// =================================================================================================

== Using pregenerated OpenAPI documents

As an alternative to generating the OpenAPI model tree from code, you can provide a valid pregenerated
OpenAPI document to describe your APIs. This document must be named `openapi` with a `yml`, `yaml`, or `json`
extension and be placed under the `META-INF` directory. Depending on the scenario, the document
might be fully or partially complete. If the document is fully complete, then you can disable
annotation scanning entirely by setting the `mp.openapi.scan.disable` MicroProfile Config property to `true`.
If the document is partially complete, then you can augment it with code.

You can find a complete OpenAPI document in the `src/main/webapp/META-INF/openapi.yaml` file.
This document is the same as your current OpenAPI document with additional APIs for the `/inventory/properties`
endpoint. To make use of this document, open this document in your favorite text editor and uncomment
all of its lines. Since this document is complete, you can also set the `mp.openapi.scan.disable` property
to `true` in the `src/main/webapp/META-INF/microprofile-config.properties` file.

[role="code_command hotspot", subs="quotes"]
----
#Update the configuration file.#
`src/main/webapp/META-INF/microprofile-config.properties`
----

[role="edit_command_text"]
Add and set the [hotspot=1]`mp.openapi.scan.disable` property to `true`.

microprofile-config.properties
[source, text, linenums, role="code_column"]
----
include::finish/src/main/webapp/META-INF/microprofile-config.properties[tags=**]
----

Run the following command and refresh the {openapi-url}[{openapi-url}^] URL to see the updated OpenAPI tree.
[role='command']
```
mvn compile
```

[source, yml, role="no_copy"]
----
/inventory/properties:
  get:
    operationId: getProperties
    responses:
      200:
        description: JVM system properties of the host running this service.
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
----


// =================================================================================================
// Testing the services
// =================================================================================================

== Testing the service

No automated tests are provided to verify the correctness of the generated OpenAPI document. Manually
verify the document by visiting the {openapi-url}[{openapi-url}^] or the {openapi-url}/ui[{openapi-url}/ui^] URL.

A few tests are included for you to test the basic functionality of the `inventory` service. If a test
failure occurs, then you might have introduced a bug into the code. These tests will run automatically
as a part of the Maven build process when you run the following command.
[role='command']
```
mvn install
```
You can also run these
tests separately from the build by using the following command, but first make sure that the server is stopped.If the server is still running from the previous steps, stop it using the Maven `liberty:stop-server` goal from command line in the `start` directory:
[role='command']
```
mvn liberty:stop-server
```

Then, verify that the tests pass using the Maven `verify` goal:
[role='command']
```
mvn verify
```

// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You have just documented and filtered the APIs of the `inventory` service from both the code and a static
file by using MicroProfile OpenAPI in Open Liberty.

Feel free to try one of the related MicroProfile guides. They demonstrate additional technologies that you
can learn and expand on top of what you built here.

For more in-depth examples of MicroProfile OpenAPI, try one of the demo applications available in the
MicroProfile OpenAPI
https://github.com/eclipse/microprofile-open-api/tree/master/tck/src/main/java/org/eclipse/microprofile/openapi/apps[GitHub repository].


include::{common-includes}/attribution.adoc[subs="attributes"]
