# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test application

on:
  pull_request:
    branches: [qa]

jobs:
  java8build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8]
    defaults:
      run:
        working-directory: finish
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - run: unset _JAVA_OPTIONS
      - name: Run tests
        run: chmod +x ../scripts/testApp.sh && ../scripts/testApp.sh
      - name: Post tests
        if: always()
        run: |
          logsPath=$(find . -name "console.log");
          cat $logsPath | grep Launching
      - name: Archive server logs if failed
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: server-logs
          path: finish/target/liberty/wlp/usr/servers/defaultServer/logs/
